"use strict";const interval=100;const observerConfig={attributes:true,childList:true,subtree:true};const observerTarget=document;const premiumTarget='#character-tools-target';const normalTarget='#character-sheet-target';const sufixTarget=' > .ct-character-sheet .ct-quick-info__ability';const compactTarget='> .ct-character-sheet .ct-skills';const premiumPrefix='ddbc';const normalPrefix='ct';const defaultPrefixes=[premiumPrefix,normalPrefix];const waitingForCharacterSheet=function(){const loadingCharacterSheet=setInterval(function(){const queryString=premiumTarget+sufixTarget+','+
normalTarget+sufixTarget+','+
premiumTarget+compactTarget+','+
normalTarget+compactTarget;const characterSheetLoaded=queryAll(queryString).length>=1;if(characterSheetLoaded){characterSheetAfterLoad();clearInterval(loadingCharacterSheet);}},interval);};const characterSheetAfterLoad=function(){replaceUnits();new MutationObserver(replaceUnits).observe(observerTarget,observerConfig);};const replaceUnits=function(mutationsList,observer){convertDistanceNumbers();convertRangeNumbers();convertUnitsInSnippets();convertDescriptions();covertSenses();convertWeightNumber();};const convertDistanceNumbers=function(){const dnDivClass='distance-number';const dnNumberClass='__number';const dnLabelClass='__label';let distances=queryAll(createMixQuery(dnDivClass,...defaultPrefixes));distances.forEach(function(el){const dnNumberSpan=el.querySelector(createMixQuery(dnDivClass+dnNumberClass,...defaultPrefixes));const dnLabelSpan=el.querySelector(createMixQuery(dnDivClass+dnLabelClass,...defaultPrefixes));replaceSimpleDistancWithMetric(el,dnNumberSpan,dnLabelSpan);});};const replaceSimpleDistancWithMetric=function(el,dnNumberSpan,dnLabelSpan){if(!checkIfMarked(el,convertedClass)){if(checkIfNotEmpty(dnNumberSpan,true)){dnNumberSpan.innerHTML=calculateMetricDistance(dnNumberSpan.innerHTML);}
if(checkIfNotEmpty(dnLabelSpan)){changeLabelToMetric(dnLabelSpan);}
markModified(el);}};const convertRangeNumbers=function(){const rnDivClass='combat-attack__range-value';const rnCloseClass='-close';const rnLongClass='-long';let distances=queryAll(createMixQuery(rnDivClass,...defaultPrefixes));distances.forEach(function(el){const rnClose=el.querySelector(createMixQuery(rnDivClass+rnCloseClass,...defaultPrefixes));const rnLong=el.querySelector(createMixQuery(rnDivClass+rnLongClass,...defaultPrefixes));replaceRangeDistanceWithMetric(el,rnClose,rnLong);});};const replaceRangeDistanceWithMetric=function(el,rnClose,rnLong){if(!checkIfMarked(el,convertedClass)){if(checkIfNotEmpty(rnClose,true)){rnClose.innerHTML=calculateMetricDistance(rnClose.innerHTML);}
if(checkIfNotEmpty(rnLong,true)){rnLong.innerHTML=replaceLongRangeDistance(rnLong.innerHTML);}
markModified(el);}};const convertDescriptions=function(){const premiumClass='.ddbc-html-content';const normalClasses='.ct-item-detail__description, '+'.ct-action-detail__description, '+'.ct-spell-detail__description, '+'.ct-snippet__content';const classes=premiumClass+', '+normalClasses;let containers=queryAll(classes);containers.forEach(function(el){replaceUnitsInTextWith(el);});};const convertUnitsInSnippets=function(){const sDivClass='.jsx-parser';let pContainers=queryAll(sDivClass);pContainers.forEach(function(el){replaceUnitsInTextWith(el);});};const replaceUnitsInTextWith=function(el){if(!checkIfMarked(el,convertedClass)){let paragraphs=queryAll('p',el);paragraphs.forEach(function(p){if(checkIfNotEmpty(p)){const textNodes=textNodesUnder(p);textNodes.forEach(function(tn){if(checkIfTextNodeNotEmpty(tn)){tn.textContent=calculateWeightInText(calculateMetricDistanceInText(tn.textContent));}});}});markModified(el);}};const covertSenses=function(){const sensesClass='.ct-senses__summary';let containers=queryAll(sensesClass);containers.forEach(function(el){el.textContent=calculateMetricDistanceInText(el.textContent);});};const convertWeightNumber=function(){const wnDivClass='weight-number';const wnNumberClass='__number';const wnLabelClass='__label';let weights=queryAll(createMixQuery(wnDivClass,...defaultPrefixes));weights.forEach(function(el){const wnNumberSpan=el.querySelector(createMixQuery(wnDivClass+wnNumberClass,...defaultPrefixes));const wnLabelSpan=el.querySelector(createMixQuery(wnDivClass+wnLabelClass,...defaultPrefixes));replaceWeightWithKilo(el,wnNumberSpan,wnLabelSpan);});};const replaceWeightWithKilo=function(el,wnNumberSpan,wnLabelSpan){if(!checkIfMarked(el,convertedClass)){if(checkIfNotEmpty(wnNumberSpan,true)){wnNumberSpan.innerHTML=calculateKiloWeight(wnNumberSpan.innerHTML);}
if(checkIfNotEmpty(wnLabelSpan)){replaceLabelWithKilo(wnLabelSpan);}
markModified(el);}};waitForSwitchToBeTriggered('bmToggleStates','csToggle',waitingForCharacterSheet);addStorageListener('bmToggleStates','csToggle',waitingForCharacterSheet);